### ISSUE TITLE
Shadowrun Support

### ISSUE THREAD

**Issue by spearwyatt14** [twonirwana/DiscordDiceBot#71]
Hey, I really love the button thing, makes it so much easier to use for my players. But, it's a pain to run sixes explode / compound with. Could you add that as an option for the Shadow Run /count successes command. It'd be a great help. 
And/or add for the /custom dice start   target pool command. Either would work.

**Comment by twonirwana** [comment]
This is for Shadowrun 2 or 3 Edition? The count_successes is not a option because you want to input the pool size and the target number. A extension for target_pool is possible but it would be a very specific solution and therefore will try to create a new command that combines the custom_dice with the option to provide multiple inputs (like target_pool).

**Comment by twonirwana** [comment]
it is now possible with `/custom_parameter start expression: {number}d6^>{target}`
